export const DELETE_BOOKMARK = 'DELETE_BOOKMARK'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'
export const FETCH_POSTS = 'FETCH_POSTS'
export const SELECT_RANDOM_ITEM = 'SELECT_RANDOM_ITEM'
export const RATING_CHANGE = 'RATING_CHANGE'

